#!/usr/bin/env python3

# ➜ lsb_release --help
# Usage: lsb_release [options]

# Options:
#   -h, --help         show this help message and exit
#   -v, --version      show LSB modules this system supports
#   -i, --id           show distributor ID
#   -d, --description  show description of this distribution
#   -r, --release      show release number of this distribution
#   -c, --codename     show code name of this distribution
#   -a, --all          show all of the above information
#   -s, --short        show requested information in short format
#
# ➜ lsb_release -a
# LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
# Distributor ID:	Ubuntu
# Description:	Ubuntu 21.04
# Release:	21.04
# Codename:	hirsute

import argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('-v',
                    '--version',
                    action='store_true',
                    help='show LSB modules this system supports')
parser.add_argument('-i', '--id', action='store_true', help='show distributor ID')
parser.add_argument('-d',
                    '--description',
                    action='store_true',
                    help='show description of this distribution')
parser.add_argument('-r',
                    '--release',
                    action='store_true',
                    help='show release number of this distribution')
parser.add_argument('-c',
                    '--codename',
                    action='store_true',
                    help='show code name of this distribution')
parser.add_argument('-a', '--all', action='store_true', help='show all of the above information')
parser.add_argument('-s',
                    '--short',
                    action='store_true',
                    help='show requested information in short format')
args = parser.parse_args()

osRelease = dict(
    l.split('=', 2) for l in Path('/etc/os-release').read_text().replace('"', '').splitlines())
# print(osRelease)

data = {
    '-': ['LSB Version:	', 'core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch'],
    'i': ['Distributor ID:	', osRelease['NAME']],  # 'Ubuntu'
    'd': ['Description:	', osRelease['PRETTY_NAME']],  # 'Ubuntu 21.04'
    'r': ['Release:	', osRelease['VERSION_ID']],  # 21.04
    'c': ['Codename:	', osRelease['VERSION_CODENAME']],  # 'hirsute'
}


def print_value(v):
    if args.short:
        print(v[1])
    else:
        print(v[0] + v[1])


if args.id:
    print_value(data['i'])
elif args.description:
    print_value(data['d'])
elif args.release:
    print_value(data['r'])
elif args.codename:
    print_value(data['c'])
elif args.all:
    print_value(data['-'])
    print_value(data['i'])
    print_value(data['d'])
    print_value(data['r'])
    print_value(data['c'])
else:
    print_value(data['-'])
